/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'Default': '默认',
    'Gain more ores based on ores.': '根据矿石获得更多矿石。',
    'Main': '首页',
    'extractors': '提取器',
    'Extractors produce ores x2 faster.': '提取器生产矿石速度x2。',
    'Efficiency': '效率',
    'Double extractor gain.': '提取器收益翻倍。',
    'Currently': '当前',
    'Amount': '数量',
    'Depth': '深度',
    'Engineering': '工程',
    'Increase the amount of modules per depth.': '增加每个深度的模块数量。',
    'Increase the depth of extractors.': '增加提取器的深度。',
    'Increase the speed of all carts and motors in the extractor.': '提高提取器中所有手推车和电机的速度。',
    'Metal boosts extractor gain.': '金属可以提高提取器的增益。',
    'Motor': '马达',
    'Scaled motor scaling starts later, and is weakened.': '缩放的电机缩放比例稍后开始，并减弱。',
    'Scaling': '缩放',
    'Self improvement': '自我提升',
    'Self-generating\'s formula is better.': '自发电的公式更好。',
    'Smelted Extractor': '冶炼萃取器',
    'Unlock the ability to upgrade extractors.': '解锁升级提取器的功能。',
    '1 furnace': '1 熔炉',
    'Bribed, uh, flames?': '贿赂，嗯，火焰？',
    'Gain 4 extra flame levels.': '获得4个额外的火焰等级。',
    'Extra Flame': '额外的火焰',
    'Embers cheapen flames.': '灰烬使火焰便宜。',
    'Multiply ember gain by extractors.': '将灰烬增益乘以提取器。',
    'Over-Engineering': '过度工程',
    'Motor boosts ember gain at a reduced rate.': '马达提升灰烬增益以一个递减的速率。',
    'Lava': '岩浆',
    'Friction': '摩擦',
    'Forged Extractor': '锻造提取器',
    'Forged Components': '锻造组件',
    'Flame Upgrades': '火焰升级',
    'Ember boost boosts ore gain at an increased rate.': '灰烬提升增强矿石收益以一个递增的速率。',
    'All components gain free levels from flame.': '所有组件均能从火焰中获得免费等级。',
    'Static Boost': '静态提升',
    'Add 2 to the motor effect base.': '马达效果基数加2。',
    'Point speed': '点数速度',
    'Oxygenator': '氧合器',
    'Gain': '收益',
    'Flamier Flames': '熊熊烈焰',
    'Flames effect is stronger.': '火焰效果更强。',
    'Flames cost scaling is weaker.': '火焰的成本比例降低。',
    'flame.': '火焰。',
    'fiery embers.': '火热灰烬。',
    'Embers': '灰烬',
    'Ember speed': '灰烬速度',
    'Ember boost': '灰烬提升',
    'Ember boost boost': '灰烬提升增强',
    'Boost ember gain.': '增强灰烬的收益。',
    'Boost point gain, and gives extra levels to the previous upgrades.': '增强灰烬增益，并为以前的升级提供更多等级。',
    'Boost ember gain, and gives extra levels to the previous upgrade.': '增强灰烬增益，并为以前的升级提供更多等级。',
    'Upgrades': '升级',
    'Hot': '热',
    'Gain x% of extractor gain per second based on your active furnaces.': '根据您的活跃熔炉，每秒获得x％的抽取器增益。',
    'Furnaces are cheaper based on metals.': '以金属为基础的熔炉更便宜。',
    'Furnace Upgrades': '熔炉升级',
    'Capture embers produced by furnaces.': '捕获熔炉产生的灰烬。',
    'furnaces': '熔炉',
    '\t\t\tUse the below slider to change active furnaces.\n\t\t\t': '\t\t\t使用下面的滑块来改变活跃的熔炉。\n\t\t\t',
    'Unlock second row of extractor upgrades.': '解锁第二行提取器升级。',
    'Unlock third row of extractor upgrades.': '解锁第三行提取器升级。',
    'Meta upgrade': '元升级',
    'Gain more ores based on upgrades.': '根据升级获得更多矿石。',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '它花费了你 {{formatTime(player.timePlayed)}} 去通关游戏。',
    '\t\tores\n\t\t': '\t\t矿石\n\t\t',
    '\t\tYou have \n\t\t': '\t\t你有 \n\t\t',
    '\t\t\tIf you would like to speedrun this, press Play Again and record your attempt, then submit on the Discord Server in the channel #speedrun-submissions.\n\t\t\t': '如果你想加速运行，请按“再次播放”并记录你的尝试，然后在Discord服务器的#speedrun-提交通道中提交',
    'Current Endgame: all competitors completed, all research upgrades gained, all researches maxed, e17 500 000 ores, e11-12 monopoly power, e45 research points': '当前终局:所有竞争对手完成，所有研究升级获得，所有研究最大，e17 500 000矿石，e11-12垄断力量，e45研究点',
    'Optimization': '优化',
    'Reset for +': '重置得到 +',
    'Self-generating': '自生产',
    'Unlock furnace upgrades.': '解锁熔炉升级。',
    'Unlock furnaces.': '解锁熔炉。',
    'Please check the Discord to see if there are new content updates!': '请查看Discord，看看是否有新的内容更新!',
    'Oh, you are still reading this?': '哦，你还在读这个?',
    'Make sure that you record the time in your stream or else your speedrun won\'t count!': '确保你记录了你的时间流，否则你的速度跑将不算数!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果花费的时间太长，则表示存在严重错误！）←',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Actual Manufacturing': '实际制造',
    'Auto-Furnace buys max furnaces.': '自动熔炉，购买最大的熔炉。',
    'Automate embers and flame respectively and they don\'t reduce ember amount if bought automatically.': '分别自动执行灰烬和火焰的操作，如果自动购买，它们不会减少灰烬的数量。',
    'Automate extractor buyables and they don\'t reduce metal amount if bought automatically.': '自动购买提取器当可购买时，并且如果自动购买，它们不会减少金属量。',
    'Automate furnaces and active furnaces respectively.': '分别自动化熔炉和活跃熔炉。',
    'Automate Manufacturers, and auto manufacturers buys max.': '使制造商自动化，制造商自动购买最大。',
    'Extractor Manufacturer': '提取器制造商',
    'Forgery': '伪造',
    'Furnace Quality Control': '熔炉质量控制',
    'Keep furnace upgrades on reset.': '重置时保留熔炉升级。',
    'manufacturers': '制造商',
    'Multiply metal gain by embers.': '用灰烬乘以金属增益。',
    'Multiply Point Speed base by 1e5.': '点速度基数乘以1e5。',
    'Point Acceleration': '点加速度',
    'Reach 80 manufacturers to unlock the next layer.': '达到80个制造商以解锁下一层。',
    'Unlock a lot of furnace and flame upgrades.': '解锁许多熔炉和火焰升级。',
    'Unlock a new column of furnace upgrades.': '解锁新的一列熔炉升级。',
    'Unlock factories.': '解锁工厂。',
    'Unlock more extractor upgrades, and keep them on reset.': '解锁更多的提取器升级，并使其保持重置状态。',
    '1 manufacturer': '1 制造商',
    'Active furnaces don\'t reduce ore amount but metal gain stays the same.': '活跃熔炉不会减少矿石量，但金属增益保持不变。',
    'Even More Optimization': '进一步优化',
    'Extractors start producing oil.': '提取器开始生产石油。',
    'Improve Depth\'s effect formula.': '改善深度的效果公式。',
    'More Optimization': '更多优化',
    'Oil Rigs Too': '石油钻机',
    'Rich In Ores': '矿石丰富',
    'The exponent for extractor gain is better.': '提取器增益的指数更好。',
    'Activate Oil Burning, which depletes your oil at twice the rate it is produced, but you gain boosts to ore gain and extra ember levels.': '激活燃油燃烧，它以两倍的速度消耗油，但是您可以提高矿石产量和增加余烬等级。',
    'Deactivate Oil Burning.': '停用燃油燃烧。',
    'Oil': '石油',
    'Ember Acceleration': '灰烬加速',
    'Ember Derivatives': '灰烬衍生物',
    'Even Flamier': '熊熊火焰',
    'Excessive Burning Practices': '过度燃烧',
    'Extracting Flames': '提取火焰',
    'Extractor gain is booster by plastic.': '提取器的增益通过塑料增强。',
    'Flame also make cheapen extractor buyables.': '火焰也使提取器的购买便宜。',
    'Flame cheapen buyables, and all cost scalings scale better.': '火焰降低了可购买物品的价格，所有的成本比例都更好。',
    'Flame Decceleration': '火焰减速',
    'Furnace smugglers': '炉子走私者',
    'Gain free flame levels from furnaces.': '从熔炉获得免费火焰等级。',
    '\t\t\tReward': '\t\t\t奖励',
    'Competitors': '竞争对手',
    'Completed': '已完成',
    'Corruptions': '贪污腐败',
    'Ember Speed\'s base is 10 times larger.': '灰烬速度的基数大10倍。',
    'exponent is always 0.2.': '指数始终为0.2。',
    'In a last bid to stop you, all softcaps and scaling are set to start at 0.': '为了阻止您，所有软上限和缩放比例都设置为从0开始。',
    'Factories are cheaper based on your mp.': '根据您的垄断力量，工厂便宜些。',
    'is disabled, and you can buy a maximum of 100 factories.': '已被禁用，您最多可以购买100家工厂。',
    'is more effective.': '更有效。',
    'Monopoly Over Land': '土地垄断',
    'Make research point gain significantly better.': '使研究点获得明显更好的收益。',
    'monopoly power': '垄断力量',
    'More lawsuits: No more furnaces!': '更多诉讼：不再有熔炉！',
    'Multiply ore gain by 1e400, but you cannot buy any upgrades past row 1 of any layer.': '将矿石收益乘以1e400，但是您不能购买任何层的第1行之后的任何升级。',
    'Multiply ore gain based on MP.': '根据垄断力量乘以矿石增益。',
    'Raise': '增加',
    'Pollutions': '污染',
    'The government has stepped in.': '官方介入了。',
    'Rioting': '骚乱',
    'The Ice Factory has just won a lawsuit against your factory. No more embers!': '制冰厂刚刚赢得了针对您的工厂的诉讼。 没有更多的余烬！',
    'They\'ve gotten even stronger, and you can only build a total of 20 factories, and this does not reset on respec. Nullify the previous challenge\'s effect, and multiplies factory costs by 1e9.': '他们变得更强大了，你只能建造20个工厂，这是没有重置的。取消前一个挑战的效果，并将工厂成本乘以1e9。',
    'to the 1.1th power.': '到第1.1力量。',
    'Unlock more monopoly upgrades.': '解锁更多的垄断升级。',
    'Unlock more upgrades, and gain more MP based on total competitor challenge completions.': '解锁更多升级，并根据竞争对手的挑战总数完成获得更多垄断力量。',
    'Wait, they still exist?': '等等，它们仍然存在吗？',
    'You can buy a total of only 20 upgrades across the previous nodes. Make sure your upgrades provide huge boosts!': '您在以前的节点中总共只能购买20个升级。 确保您的升级可以带来巨大的提升！',
    'You come to find your space for factories taken by a competitor.': '你发现你的工厂空间被竞争对手占据了。',
    'does nothing.': '什么也不做。',
    'The plastic has piled itself up into mountains, and hindering your extractor\'s progress. Square root extractor and ore gain, and': '塑料已经堆积成山，阻碍了萃取器的前进。 平方根提取器和矿石增益，以及',
    'To add to the previous pollution, global warming has gotten so bad that 99.999% of your extractors, plastic, bricks, and ores are melting every second.': '除了以前的污染外，全球变暖已变得如此严重，以至于99.999％的提取器，塑料，砖块和矿石每秒都在融化。',
    'To add to the previous pollution, the embers have burned through the plastic, and you they\'re autobuying their buyables without your command. Embers^0.5 divide plastic and ore gain.': '为了增加之前的污染，灰烬已经烧穿了塑料，而你他们在没有你命令的情况下自动购买他们的可购买物品。余烬^0.5除塑料和矿石增益。',
    'Improve the 5th milestone to gain 200%.': '改善第5个里程碑，获得200％的收益。',
    'is 2x stronger in pollutions (but': '污染强度提高了2倍（但',
    'is quartered from phase Ⅱ onwards).': '从阶段Ⅱ开始驻扎)。',
    'Landscape of Horrendousness': '恐怖景观',
    'Monopoly Over Layers': '分层垄断',
    'Monopoly Over Manufacturing': '制造业垄断',
    'Ores are Trash': '矿石是垃圾',
    'Perpetual Monopoly': '永久垄断',
    'Polluted Monopoly': '污染垄断',
    'Post-100 manufacturer scaling is 30% weaker.': '100后制造商的规模缩小了30％。',
    'Retain milestones on row 2 nodes.': '保留第2行节点上的里程碑。',
    'Retain upgrades from the previous layers.': '保留先前各层的升级。',
    'The automator buys max factories.': '这个自动器买下了最多的工厂。',
    'The Government is your competitor': '政府是你的竞争对手',
    'Triple MP gain.': '垄断力量增益增加三倍。',
    'Unlock plastic structures.': '解锁塑料结构。',
    'Unlock pollutions.': '解锁污染。',
    'Unlock the final two competitor challenges.': '解锁最后两个竞争对手的挑战。',
    'Unlock two new layers.': '解锁两个新层。',
    'Waste boosts ore gain.': '废物增加了矿石的获取。',
    'Eww Static Boosts': '静态静电提升',
    'Factories no longer make each other more expensive.': '工厂不再使彼此变得更昂贵。',
    'Main researches': '主要研究',
    'Oil burning halves oil production instead, is always activated, and the effects are much more powerful.': '取而代之的是，燃油燃烧可将石油产量减半，而且效果更强大。',
    'Power stations reset nothing.': '发电厂什么也没有重置。',
    'Purchase a scientist.': '购买一名科学家。',
    'Research automation': '研究自动化',
    'research points': '研究点',
    'Researches': '研究成果',
    'Scientists': '科学家',
    'Scientists are much cheaper, and halve all research times again.': '科学家便宜得多，并且将所有研究时间再减少一半。',
    'The Burning Tree': '燃烧树',
    'Timewalled Gaming again': '限时游戏再次',
    'Unlock automatic research.': '解锁自动研究。',
    'Untimewall Gaming': '永不过时的游戏',
    'Autobuy electric buyables, and they don\'t reduce electricity. Electric buyables are also much cheaper.': '自动购买可购买的电力，并且它们不会减少电力。 电购品也便宜得多。',
    'Automatically research, and researching resets nothing. Research point gain is much better, and halve all research times.': '自动进行研究，研究不会重设任何内容。 研究点增益要好得多，并且可以将所有研究时间减少一半。',
    'disabled': '禁用',
    'Free Plastic Strucutres add free levels to all structures, and autobuy plastic structures. Swindles the goverment into giving you infinity space for plastic structures instead of the 20 cap.': '自由塑料结构为所有结构添加自由水平，并自动购买塑料结构。 诱使政府为您提供用于塑料结构的无限空间，而不是20上限的空间。',
    '\t\t\t\tAll researches have been capped at 50 for balancing purposes.': '\t\t\t\t为了平衡起见，所有研究的上限均为50。',
    'One-time researches': '一次性研究',
    '\t\t\t\tAllocate scientists to researches using the following slider.': '\t\t\t\t使用以下滑块分配科学家进行研究。',
    '\t\t\t\tResearches boost the gain of various resources, but take a certain amount of time to complete. This time is better the more scientists you have allocated in the research.': '\t\t\t\t研究可以提高各种资源的利用率，但需要一定的时间才能完成。 这次您分配的科学家越多越好。',
    '\t\t\t\tYou cannot disable a research after activating it!': '\t\t\t\t激活研究后，您将无法禁用它！',
    'Boosts all waste generations.': '促进所有废物的产生。',
    'Boosts electricity generation.': '促进发电。',
    'Boosts extractor gain.': '提高提取器增益。',
    'Boosts oil generation.': '促进石油产生。',
    'Boosts ore generation.': '促进矿石产生。',
    'Boosts heat generation.': '促进热量产生。',
    'Automate Factories, and non active manufacturers produce bricks at half the rate.': '使工厂自动化，并且不活跃的制造商以一半的速度生产砖块。',
    'Buildings of Horrendousness': '可怕的建筑',
    'Corruptions boosts embers at a reduced rate.': '腐败会以较低的速度增加余烬。',
    'Exponentiate ore gain (after the previous layers\' boosts) based on total mp.': '根据总垄断力量估算矿石增益（在前几层提升之后）。',
    'Furnaces and Manufacturers reset nothing.': '熔炉和制造商什么也不复位。',
    'Gain 10% of monopoly power gain per second.': '每秒获得10％的垄断力量增益。',
    'has just won a lawsuit against your factory. No more embers!': '刚刚赢得了对你的工厂提起诉讼。 没有更多的余烬！',
    'Heat boosts burning waste generation, and burning waste boosts embers.': '热能促进燃烧废物的产生，而燃烧废物则促进余烬。',
    'Automate power stations.': '自动化发电站。',
    'Increase the resistance to produce more heat.': '增加阻力，以产生更多的热量。',
    'Increase the voltage.': '增加电压。',
    'ing gold': 'ing黄金',
    'More Voltage, More Destruction': '更多电压，更多破坏',
    'power stations': '发电站',
    'Produce 10x more greenhouse gas.': '多产生10倍的温室气体。',
    'Produce more ores based on electricity.': '依靠电力生产更多的矿石。',
    'Resistance': '电阻',
    'Spark': '火花',
    'Synergism': '协同',
    'The Unsustainable Factoree': '不可持续的工厂',
    'Voltage': '电压',
    'Voltage has a better effect.': '电压效果更好。',
    'Factories': '工厂',
    'Bribed furnaces has a better effect formula.': '贿赂炉有较好的效果公式。',
    'Cheapen furnaces based on time spent in row 2 reset.': '根据在第 2 行重置中花费的时间来降低熔炉的价格。',
    'Furnace cost scaling base scales better.': '炉子成本降低比例更好。',
    'Make metal gain better, and boost extractor gain based on furnaces.': '使金属增益更好，并根据熔炉提高提取器增益。',
    'Point Jerk': '点数混蛋',
    'Point Acceleration is stronger based on furnaces.': '基于熔炉的点数加速更强。',
    'Oil burning makes flames cheaper.': '燃油燃烧使火焰更便宜。',
    'Steel': '钢',
    'Timewall gaming': '时间墙游戏',
    'Multiply the base of Ember Speed by 5.': '将余烬速度的基数乘以5。',
    'Bribed furnaces': '受贿熔炉',
    'Evaded furnaces': '回避熔炉',
    'Laundered furnaces': '清洗熔炉',
    'Powerful furnaces': '给力熔炉',
    'Raise Ember gain to an exponent.': '提高灰烬增益到一个指数。',
    'Make oil burning better based on plastic.': '使基于塑料的油燃烧更好。',
    'Makes factories cheaper based on plastic.': '使基于塑料的工厂更便宜。',
    'plastic': '塑料',
    'Plastic structures': '塑料结构',
    'Questionable Burning Practices': '可疑的燃烧行为',
    'Structurally dangerous factories': '结构危险的工厂',
    'Uncontrolled burn': '不受控制的燃烧',
    'Unlock the fourth ember buyable, unaffected by extra levels.': '解锁第四个可购买的余烬，不受额外等级的影响。',
    '\t\t\tActive manufacturers subtract from the manufacturer effect, but in turn you get bricks to buy factories.\n\t\t\t': '\t\t\t活跃的制造商从制造商效应中减去，但反过来你会得到砖头来购买工厂。\n\t\t\t',
    '\t\t\tUse the below slider to change active manufacturers.\n\t\t\t': '\t\t\t使用下面的滑块更改活跃的制造商。\n\t\t\t',
    'Brick Manufacturing': '砖制造',
    'Buying a factory makes all others more expensive. Use the space you have wisely.': '购买工厂会使所有其他工厂变得更加昂贵。 明智地使用您拥有的空间。',
    'Creates a furnace every 1 second. (count toward scaling) Fifth level nerfs ore to metal softcap. Also increases furnaces cap.': '每 1 秒制造一个熔炉。 （计入缩放）第五级 削弱 矿石到金属软帽。 还增加了熔炉上限。',
    'Each level increases brick gain.': '每升一级增加砖块增益。',
    'First level unlocks plastic, other levels boost plastic gain.': '第一级解锁塑料，其他级数提高塑料增益。',
    'research points\t\t\n\t\t': '研究点\t\t\n\t\t',
    'Produce bricks 10x faster.': '以10倍的速度生产砖块。',
    'Factory 1\'s interval is reduced to 0.5 seconds.': '工厂1的间隔缩短到0.5秒。',
    'Factory one raises furnace hardcap to 100 instead of 50 per level.': '工厂一将熔炉硬上限提高到 100，而不是每级 50。',
    'e: Reset for extractors': 'e：提取器重置',
    'f: Reset for furnaces': 'f: 重置熔炉',
    'm: Reset for manufacturers': 'm：重置制造商',
    'o: Toggle oil burning': 'o：切换油燃烧',
    'p: reset for power stations': 'p: 电站重置',
    'r: reset for research points': 'r：重置研究点',
    'shift+f: Buy flame': 'shift+f：购买火焰',
    'Please deactivate pollution in another phase before activating this pollution.': '在激活此污染之前，请在另一个阶段停用污染。',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '已开',
    'OFF': '已关',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'Main Prestige Tree server': '主声望树服务器',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Boost ember gain by ": "通过提高灰烬收益 ",
    "Multiply the base of Ember Boost by ": "将灰烬提升的基数乘以",
    "Manufacturer of flames (": "火焰制造商 (",
    "Manufacturer of furnace upgrades (": "熔炉升级制造商 (",
    "Manufacturer of furnaces (": "熔炉制造商 (",
    "Manufacturer of parts (": "零件制造商 (",
    "Mass production of furnaces (": "大规模生产熔炉 (",
    "Meta Manufacturer (": "元制造商 (",
    "\t\t\tFiller": "\t\t\t过滤器",
    "Anti-factoree ": "反工厂 ",
    "The Ice Factory ": "制冰厂",
    "The Spacious Factory ": "宽敞的工厂",
    "The Upgrade Factory ": "升级工厂 ",
    "Pollution: Phase ": "污染：阶段 ",
    "One-time Research ": "一次性研究 ",
    ", boosting monopoly power gain by ": "，提高垄断力量增益 ",
    "Questionable Structural Integrity": "可疑的结构完整性",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "Why did I choose this life": "我为什么选择这样的生活",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^x([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.,]+)$/,
    /^\/([\d\.,]+)$/,
    /^\/([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e(\d+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^Cost\: (.+) extractors\n\t\t$/, '成本\: $1 提取器\n\t\t'],
    [/^Cost\: (.+) manufacturers\n\t\t$/, '成本\: $1 制造商\n\t\t'],
    [/^Cost\: (.+) furnaces\n\t\t$/, '成本\: $1 熔炉\n\t\t'],
    [/^Cost\: (.+) monopoly power\n\t\t$/, '成本\: $1 垄断力量\n\t\t'],
    [/^Cost\: (.+) burningWaste\n\t\t$/, '成本\: $1 燃烧废物\n\t\t'],
    [/^Cost\: (.+) heat\n\t\t$/, '成本\: $1 热量\n\t\t'],
    [/^Cost\: (.+) oil\n\t\t$/, '成本\: $1 石油\n\t\t'],
    [/^Cost\: (.+) bricks\n\t\t$/, '成本\: $1 砖头\n\t\t'],
    [/^Cost\: (.+) plastic\n\t\t$/, '成本\: $1 塑料\n\t\t'],
    [/^Cost\: (.+) electricity\n\t\t$/, '成本\: $1 电力\n\t\t'],
    [/^Cost\: (.+) waste\n\t\t$/, '成本\: $1 废物\n\t\t'],
    [/^Cost\: (.+) research points\n\t\t$/, '成本\: $1 研究点\n\t\t'],
    [/^\t\t\t\tCost: (.+) research points$/, '\t\t\t\t成本: $1 研究点'],
    [/^\t\t\t\tCurrently: (.+) researches\n\t\t\t\tEffect: (.+)\n\t\t\t\t$/, '\t\t\t\t当前: $1 研究\n\t\t\t\t效果: $2\n\t\t\t\t'],
    [/^\t\t\t\tCurrently: (.+) researches\n\t\t\t\tEffect: (.+)\n\t\t\t\tTime left: (.+)s$/, '\t\t\t\t当前: $1 研究\n\t\t\t\t效果: $2\n\t\t\t\t时间剩余: $3秒'],
    [/^\t\t\t\tCurrently: (.+) researches\n\t\t\t\tEffect: (.+)\n\t\t\t\tTime left: Infinitys$/, '\t\t\t\t当前: $1 研究\n\t\t\t\t效果: $2\n\t\t\t\t时间剩余: 无限'],
    [/^\t\t\t\tCurrently: (.+) volts\n\t\t\t\tCost: (.+)\n\t\t\t\tEffect: (.+) to electricity and heat$/, '\t\t\t\t当前: $1 伏\n\t\t\t\成本: $2\n\t\t\t\t效果: $3 到电力和热量'],
    [/^\t\t\t\tCurrently: (.+) ohms\n\t\t\t\tCost: (.+)\n\t\t\t\tEffect: (.+) to heat$/, '\t\t\t\t当前: $1 欧姆\n\t\t\t\成本: $2\n\t\t\t\t效果: $3 到热量'],
    [/^Currently: (.+) researches\n\t\t\t\tEffect: (.+)\n\t\t\t\t$/, '\t\t\t\t当前: $1 研究\n\t\t\t\t效果: $2\n\t\t\t\t'],
    [/^Cost\: (.+) flame\n\t\t$/, '成本\: $1 烈焰\n\t\t'],
    [/^Next at (.+) ores$/, '下一个在 $1 矿石'],
    [/^You have (.+) ores$/, '你有 $1 矿石'],
    [/^Ⅰ is currently active. Click here to deactive this pollution and gain (.+) plastic pollutants \(log10\(plastic\)\).$/, 'Ⅰ目前处于活动状态。 单击此处可消除这种污染并获得 $1 塑料污染物（log10（塑料））。'],
    [/^Ⅱ is currently active. Click here to deactive this pollution and gain (.+) incinerators \(√manufacturers\).$/, 'Ⅱ目前处于活动状态。 单击此处消除这种污染并获得 $1 个焚烧炉（√制造商）。'],
    [/^Ⅲ is currently active. Click here to deactive this pollution and gain (.+) chimneys \(power stations\).$/, 'Ⅲ目前处于活动状态。 单击此处消除这种污染并获得 41 个烟囱（发电站）。'],
    [/^You have (.+) free structures.\n\t\t\t\t$/, '你有 $1 自由结构.\n\t\t\t\t'],
    [/^Req\: (.+) ores\t\t\n\t\t$/, '需要\: $1 矿石\t\t\n\t\t'],
    [/^Req\: (.+) \/ (.+) metals\t\t\n\t\t$/, '需要\: $1 \/ $2 金属\t\t\n\t\t'],
    [/^Req\: (.+) \/ (.+) ores\t\t\n\t\t$/, '需要\: $1 \/ $2 矿石\t\t\n\t\t'],
    [/^(.+) \/ (.+) ores\t\t\n\t\t$/, '$1 \/ $2 矿石\t\t\n\t\t'],
    [/^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+) metals\t\t\n\t\t$/, '$1e$2 \/ $3e$4 金属\t\t\n\t\t'],
    [/^You have (.+) metals.\n\t\t\t$/, '你有 $1 金属.\n\t\t\t'],
    [/^\t\t\tYou have (.+) active furnaces.\n\t\t\t$/, '你有 $1 活跃的熔炉'],
    [/^, boosting ore gains by (.+) and ember gains by (.+)$/, '，将矿石收益提高$1，将灰烬收益提高$2'],
    [/^You have made a total of (.+) monopoly power$/, '您总共拥有 $1 的垄断权'],
    [/^\t\t\t\tNext research will allocate (.+) scientists.\n\t\t\t\t$/, '\t\t\t\t下一步研究将分配 $1 位科学家。\n\t\t\t\t'],
    [/^\t\t\t\tResearch time: (.+)s$/, '\t\t\t\t研究时长: $1秒'],
    [/^(\d+) m.$/, '$1 制造商'],
    [/^(\d+) power stations$/, '$1 发电站'],
    [/^([\d\.]+)e([\d\.,]+) oil$/, '$1e$2 石油'],
    [/^([\d\.,]+) oil$/, '$1 石油'],
    [/^\t\t\tGoal: (.+) ores$/, '\t\t\t目标: $1 矿石'],
    [/^, boosting brick gain by (.+) \(based on total mp$/, '，将砖块收益提高$1（基于总mp'],
    [/^This is further boosted by your burning waste, providing a (.+) multiplier to electricity gain.\n\t\t\t\t$/, '这是进一步推动你的燃烧废物，提供 $1 倍的电力增益'],
    [/^You are producing (.+) electricity per second. \(boosted by oil burning\)\n\t\t\t\t$/, '你每秒产生 $1 的电。\(由燃油推动\)\n\t\t\t'],
    [/^You have (.+) electricity, producing (.+) heat per second.$/, '你有 $1 的电，每秒产生 $2 的热量。'],
//    [/^(.+) furnaces$/, '$1 熔炉'],
    [/^\t\t\t\tAmount: (.+)\n\t\t\t\tCurrently: (.+) to bricks\n\t\t\t\tCost: (.+) bricks$/, '\t\t\t\t数量: $1\n\t\t\t\t当前: $2 到砖头\n\t\t\t\t成本: $3 砖头'],
    [/^\t\t\t\tAmount: (.+)\n\t\t\t\tCurrently: (.+) to plastic\n\t\t\t\tCost: (.+) bricks$/, '\t\t\t\t数量: $1\n\t\t\t\t当前: $2 到塑料\n\t\t\t\t成本: $3 砖头'],
    [/^Amount: (.+)\n\t\t\t\tCost: (.+)$/, '数量: $1\n\t\t\t\t成本: $2'],
    [/^\t\t\t\tYou have (.+) structures to furnace smuggling, making factory (.+) softcap start (.+) later.\n\t\t\t\t$/, '\t\t\t\t您有 $1 结构可用于走私熔炉，使工厂 $2 软上限在 $3 之后开始。\n\t\t\t\t'],
    [/^\t\t\t\tYou have (.+) structures to structurally dangerous factories, making post-1000 factory scaling start (.+) later.\n\t\t\t\t$/, '\t\t\t\t你有$1个结构去构造危险的工厂，使1000后的工厂比例开始$2后。\n\t\t\t\t'],
    [/^\t\t\t\tYou have (.+) structures to uncontrolled burning, making post-250 ember speed scaling start (.+) later.$/, '你有$1个不受控制燃烧的结构，使250余烬速度增加后开始$2。'],
    [/^(.+) fiery embers$/, '$1 火热灰烬'],
    [/^\t\t\t\tAmount: (.+)\n\t\t\t\tCurrently: (.+)\/s\n\t\t\t\tCost: (.+) bricks\n\t\t\t\tFurnaces capped at (.+)$/, '\t\t\t\t数量: $1\n\t\t\t\t当前: $2\/秒\n\t\t\t\t成本: $3 砖头\n\t\t\t\t熔炉上限为 $4'],
    [/^Research (\d+)$/, '研究 $1'],
    [/\t\t\t\tYou have (.+) greenhouse gas, boosting burning waste gain by (.+), and raising all waste effects to \^(.+).$/, '\t\t\t\t你有 $1 温室气体，增加燃烧废物增益 $2，所有废物效应增加 \^$3。'],
    [/^Currently\: (\d+)\+([\d\.]+)\n\t\t\t\tCost\: (.+) fiery embers\n\t\t\t\tEffect\: x(.+)$/, '当前\: $1\+$2\n\t\t\t\t成本\: $2 火热灰烬\n\t\t\t\t效果\: x$3'],
    [/^Currently\: (\d+)\n\t\t\t\tCost\: (.+) fiery embers\n\t\t\t\tEffect\: x(.+)$/, '当前\: $1 深度\n\t\t\t\t成本\: $2 火热灰烬\n\t\t\t\t效果\: x$3'],
    [/^Currently\: (.+)\n\t\t\t\tCost\: (.+) fiery embers\n\t\t\t\tEffect\: (.+)$/, '当前\: $1 深度\n\t\t\t\t成本\: $2 火热灰烬\n\t\t\t\t效果\: x$3'],
    [/^Currently\: (.+) deep\n\t\t\t\tCost\: (.+) metals\n\t\t\t\tEffect\: x(.+)$/, '当前\: $1 深度\n\t\t\t\t成本\: $2 金属\n\t\t\t\t效果\: x$3'],
    [/^Currently\: (.+)rpm\n\t\t\t\tCost\: (.+) metals\n\t\t\t\tEffect\: x(.+)$/, '当前\: $1 rpm\n\t\t\t\t成本\: $2 金属\n\t\t\t\t效果\: x$3'],
    [/^Currently\: (.+) modules\n\t\t\t\tCost\: (.+) metals\n\t\t\t\tEffect\: x(.+)$/, '当前\: $1 模块\n\t\t\t\t成本\: $2 金属\n\t\t\t\t效果\: x$3'],
    [/^You are losing (.+) oil per second, but you gain a x(.+) boost to ore gain and get (.+) extra ember buyable levels.$/, '您每秒损失 $1 石油，但获得的矿石收益增加了 x$2 ，并获得了 $3 额外的余烬可购买等级。'],
    [/^(.+) to burning waste, (.+) to embers$/, '$1 为燃烧废物，$2 为余烬'],
    [/^Factory ([\d\.]+)$/, '工厂 $1'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1 分 $2 秒'],
    [/^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/, '$1 时 $2分 $3 秒'],
    [/^You have (.+) incinerators, producing (.+) burning waste per second.$/, '你有$1个焚烧炉，每秒产生$2燃烧垃圾。'],
    [/^You have (.+) bricks. \((.+)\/s\)\n\t\t\t$/, '你有 $1 砖块. \($2\/秒\)\n\t\t\t'],
    [/^(.+)\/sec$/, '$1\/秒'],
    [/^Time Played: (.+)d (.+)h (.+)m (.+)s$/, '玩了多久: $1天 $2小时 $3分钟 $4秒'],
    [/^\t\t\t\tYou have (.+) scientists.$/, '\t\t\t\t你有 $1 科学家.'],
    [/^(.+) monopoly power$/, '$1\/秒'],
    [/^\t\t\tYou have (.+) active manufacturers.\n\t\t\t$/, '\t\t\t您有 $1 个活动制造商。\n\t\t\t'],
    [/^You have (.+) free scientists.$/, '你有 $1 空闲科学家'],
    [/^You have (.+) chimneys, producing (.+) greenhouse gases per second.$/, '您有 $1 烟囱，每秒产生 $2 温室气体。'],
    [/^You have (.+) plastic pollutants, producing (.+) waste per second.$/, '你有 $1 个塑料污染物，每秒钟产生 $2 个废物。'],
    [/^You have (.+) waste, boosting plastic gain by (.+) and making manufacturers cheaper by \/(.+).$/, '你有 $1 垃圾，增加塑料增益 $2，使制造商更便宜 \/$3。'],
    [/\t\t\t\tYou have (.+) burning waste, boosting waste gain by (.+).$/, '\t\t\t\t您有 $1 燃烧废物，提升废物收益 $2。'],
    [/^\t\t\t\t\((.+)\/s\)\n\t\t\t\t$/, '\t\t\t\t\($1\/秒\)\n\t\t\t\t'],
    [/You have (.+) heat, boosting ember production by (.+), and multiplying point speed base by (.+)$/, '你有 $1 的热量，增加余烬产量 $2，点速度基数乘以 $3'],
    [/You have (.+) oil, boosting ember gains by x(.+)$/, '你有 $1 的石油，增加余烬收益 x$2'],
    [/^flame, making the cost exponent of all ember upgrades divided by (.+).\n\t\t\t$/, '火焰，使所有灰烬升级的成本指数除以 $1。\n\t\t\t'],
    [/^You lose a certain amount of ores per second, but your furnaces convert them into metals. \n\t\t\tYour points are divided by (.+) per second, but for every point you lose you gain (.+) metals.\n\t\t\t$/, '你每秒损失一定数量的矿石，但是你的熔炉把它们转化成金属。你的点数每秒除以 $1，但是你每失去一点，你就获得 $2 金属。\n\t\t\t'],
    [/^([\d\.]+)e(\d+) extractors$/, '$1e$2 提取器'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);